name: flutter_app
description: "flutter开发的软件"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.2
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  video_player: # 视频播放鸿蒙适配版
    git:
      url: "https://gitcode.com/openharmony-sig/flutter_packages.git"
      path: "packages/video_player/video_player"
  path_provider: # 路径
  shared_preferences: # 本地存储鸿蒙适配版
    git:
      url: "https://gitcode.com/openharmony-sig/flutter_packages.git"
      path: "packages/shared_preferences/shared_preferences"
  dio: ^5.8.0+1 # 网络请求
  loading_more_list: ^7.1.0 # 上拉加载更多
  cached_network_image: ^3.4.1

dependency_overrides:
  path_provider:
    git:
      url: "https://gitcode.com/openharmony-sig/flutter_packages.git"
      path: "packages/path_provider/path_provider"

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  # 没有这行代码，自带图标显示不出来
  uses-material-design: true
