name: awesome_flutter
description: "flutter开发的软件"
publish_to: "none"

version: 2025.8.3+2

environment:
  sdk: ^3.6.2
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fluttertoast: # 轻提示
    git:
      url: "https://gitcode.com/openharmony-sig/flutter_fluttertoast.git"
  video_player: # 视频播放鸿蒙适配版
    git:
      url: "https://gitcode.com/openharmony-sig/flutter_packages.git"
      path: "packages/video_player/video_player"
  path_provider: # 路径
  shared_preferences: # 本地存储鸿蒙适配版
    git:
      url: "https://gitcode.com/openharmony-sig/flutter_packages.git"
      path: "packages/shared_preferences/shared_preferences"
  auto_orientation: # 屏幕旋转
    git:
      url: "https://gitcode.com/openharmony-sig/fluttertpc_auto_orientation"
  dio: ^5.8.0+1 # 网络请求
  loading_more_list: ^7.1.0 # 上拉加载更多
  cached_network_image: ^3.4.1 # 图片缓存
  timeago: ^3.7.1 # 时间
  crypto: ^3.0.6 # 加密
  qr_flutter: ^4.1.0 # 二维码
  extended_nested_scroll_view: ^6.2.1 # 解决sliver滑动不同步
  screen_brightness: ^2.1.5 # 屏幕亮度
  volume_controller: ^3.4.0 # 音量控制
  universal_platform: # 平台判断，适配鸿蒙
    git:
      url: "https://github.com/qinshah/flutter-universal-platform.git"
  flutter_svg: ^2.2.0 # svg图标

dependency_overrides:
  path_provider:
    git:
      url: "https://gitcode.com/openharmony-sig/flutter_packages.git"
      path: "packages/path_provider/path_provider"

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  # 没有这行代码，自带图标显示不出来
  uses-material-design: true
